language: objective-c

script:
  - xctool -workspace downloader.xcworkspace -scheme downloader -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace downloader.xcworkspace -scheme downloaderTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
